# Generated by Django 5.0.6 on 2024-06-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electroapp', '0002_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(upload_to='media/'),
        ),
    ]
