# Generated by Django 5.0.6 on 2024-06-20 10:52

import electroapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electroapp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(null=True, upload_to=electroapp.models.get_file_path),
        ),
    ]
