# Generated by Django 5.0.6 on 2024-06-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electroapp', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pimage',
            field=models.FileField(null=True, upload_to='productfile'),
        ),
    ]
