# Generated by Django 5.0.6 on 2024-06-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electroapp', '0007_product_category_product_description_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pname',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='qty',
        ),
        migrations.AddField(
            model_name='order',
            name='pdetail',
            field=models.JSONField(max_length=255, null=True),
        ),
    ]
